version: '3'

services:
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8999:8000"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'sspanel'
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql
